name: azimuth-fm
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # Core scientific stack
  - numpy
  - scipy
  - pandas
  - tqdm
  # Audio I/O helpers (wav saving/reading)
  - libsndfile
  - sox
  - ffmpeg
  # PyTorch + CUDA (bundled CUDA 12.1 libs; no module load required)
  - pytorch=2.4.*
  - torchvision=0.19.*
  - torchaudio=2.4.*
  - pytorch-cuda=12.1
  # Config management
  - hydra-core=1.3.*
  - omegaconf=2.3.*
  # Optional logging
  - pip:
      - wandb>=0.16
