# Top-level defaults for Hydra
defaults:
  - _self_
  - data: default
  - stft: default
  - model: default
  - train: default
  - sample: default
  - eval: default

# Hydra output dir control (put Hydra logs under runs/)
hydra:
  run:
    dir: runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false
