train_csv: /parallel_scratch/yc01847/whitenoise_binaural_kemar_fm/manifestsmetadata_train.csv
val_csv:   /parallel_scratch/yc01847/whitenoise_binaural_kemar_fm/manifestsmetadata_val.csv
audio_root: /parallel_scratch/yc01847/whitenoise_binaural_kemar_fm
sr: 16000
seg_sec: 1.5

az_mode: sincos        # or "deg" if you want the old behavior
enforce_csv_sr: true