steps: 20000
batch_size: 64
num_workers: 4
lr: 2e-4
val_every: 1000
save_every: 2000
sample_steps: 40
out_dir: runs/fm16k
device: cuda
seed: 0
amp: true
grad_clip: 1.0

# Validation sampling controls
val_dump_audio: true
val_sample_degs: [0, 30, 48, 60, 72, 90, 281, 330]
val_show_steps: [8, 20, 40]

wandb:
  enable: false
  project: azimuth-fm
  log_audio: false
  max_audio: 10
  upload_artifacts: false
  artifact_prefix: azfm
  artifact_ckpt_every: 2000
  artifact_audio_every: 1000
